/**
 * This file is autogenerated by W3Final Scaffold.
 * You should not edit it manually or your changes might be overwritten.
 */
import type { GenericContractsDeclaration } from '../utils/contractTypes.js';

const externalContracts = {} as const;

export default externalContracts satisfies GenericContractsDeclaration;

